#!/usr/bin/env bash
set -euo pipefail
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -a
[[ -f "$APP_DIR/.env" ]] && source "$APP_DIR/.env"
set +a

RESPECT_CLOUDPANEL_PORT="${ARGWS_PONTO_MANAGER_RESPECT_CLOUDPANEL_PORT:-true}"
WEB_PORT="${ARGWS_PONTO_MANAGER_WEB_PORT:-61002}"
if [[ "$RESPECT_CLOUDPANEL_PORT" =~ ^(1|true|TRUE|yes|YES|sim|SIM|on|ON)$ ]] && [[ -n "${PORT:-}" ]]; then
  WEB_PORT="$PORT"
fi

cat <<PORTS
Portas configuradas:

API Headless:
  Host: ${ARGWS_PONTO_MANAGER_API_HOST:-127.0.0.1}
  Porta: ${ARGWS_PONTO_MANAGER_API_PORT:-61001}
  URL: http://${ARGWS_PONTO_MANAGER_API_HOST:-127.0.0.1}:${ARGWS_PONTO_MANAGER_API_PORT:-61001}

Web / Browser / WebPort:
  Host: ${ARGWS_PONTO_MANAGER_WEB_HOST:-127.0.0.1}
  Porta: $WEB_PORT
  URL: http://${ARGWS_PONTO_MANAGER_WEB_HOST:-127.0.0.1}:$WEB_PORT

Webhook:
  Habilitado: ${ARGWS_PONTO_MANAGER_WEBHOOK_ENABLED:-false}
  Host: ${ARGWS_PONTO_MANAGER_WEBHOOK_HOST:-127.0.0.1}
  Porta: ${ARGWS_PONTO_MANAGER_WEBHOOK_PORT:-61003}
  URL: http://${ARGWS_PONTO_MANAGER_WEBHOOK_HOST:-127.0.0.1}:${ARGWS_PONTO_MANAGER_WEBHOOK_PORT:-61003}${ARGWS_PONTO_MANAGER_WEBHOOK_BASE_PATH:-/webhooks}

WebSocket:
  Habilitado: ${ARGWS_PONTO_MANAGER_WEBSOCKET_ENABLED:-false}
  Host: ${ARGWS_PONTO_MANAGER_WEBSOCKET_HOST:-127.0.0.1}
  Porta: ${ARGWS_PONTO_MANAGER_WEBSOCKET_PORT:-61004}
  URL: ws://${ARGWS_PONTO_MANAGER_WEBSOCKET_HOST:-127.0.0.1}:${ARGWS_PONTO_MANAGER_WEBSOCKET_PORT:-61004}${ARGWS_PONTO_MANAGER_WEBSOCKET_PATH:-/ws}

Publicar todas as portas: ${ARGWS_PONTO_MANAGER_PUBLISH_ALL_PORTS:-false}
Iniciar todas as portas: ${ARGWS_PONTO_MANAGER_START_ALL_PORTS:-false}
Respeitar PORT do CloudPanel: ${ARGWS_PONTO_MANAGER_RESPECT_CLOUDPANEL_PORT:-true}
PORTS
