#!/usr/bin/env bash
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PID_FILE="$APP_DIR/argws-ponto-manager.pid"
LOG_DIR="$APP_DIR/logs"
LOG_FILE="$LOG_DIR/argws-ponto-manager.log"
ENV_FILE="$APP_DIR/.env"

mkdir -p "$LOG_DIR" "$APP_DIR/data"

set -a
[[ -f "$ENV_FILE" ]] && source "$ENV_FILE"
set +a

bool_true() {
  case "${1:-}" in
    1|true|TRUE|yes|YES|sim|SIM|on|ON) return 0 ;;
    *) return 1 ;;
  esac
}

BIN_PATH="${ARGWS_PONTO_MANAGER_BINARY:-$APP_DIR/bin/argws_ponto_manager}"
if [[ "$BIN_PATH" != /* ]]; then
  BIN_PATH="$APP_DIR/${BIN_PATH#./}"
fi

if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "Ponto Manager já está em execução. PID: $(cat "$PID_FILE")"
  exit 0
fi

if [[ ! -x "$BIN_PATH" ]]; then
  echo "Binário não encontrado ou sem permissão de execução: $BIN_PATH"
  echo "Execute: chmod +x $APP_DIR/bin/argws_ponto_manager"
  exit 1
fi

PUBLISH_ALL_PORTS="${ARGWS_PONTO_MANAGER_PUBLISH_ALL_PORTS:-false}"
START_ALL_PORTS="${ARGWS_PONTO_MANAGER_START_ALL_PORTS:-false}"
RESPECT_CLOUDPANEL_PORT="${ARGWS_PONTO_MANAGER_RESPECT_CLOUDPANEL_PORT:-true}"
PUBLIC_BIND_HOST="${ARGWS_PONTO_MANAGER_PUBLIC_BIND_HOST:-0.0.0.0}"

if bool_true "$PUBLISH_ALL_PORTS"; then
  export ARGWS_PONTO_MANAGER_API_HOST="${ARGWS_PONTO_MANAGER_API_HOST:-$PUBLIC_BIND_HOST}"
  export ARGWS_PONTO_MANAGER_WEB_HOST="${ARGWS_PONTO_MANAGER_WEB_HOST:-$PUBLIC_BIND_HOST}"
  export ARGWS_PONTO_MANAGER_WEBHOOK_HOST="${ARGWS_PONTO_MANAGER_WEBHOOK_HOST:-$PUBLIC_BIND_HOST}"
  export ARGWS_PONTO_MANAGER_WEBSOCKET_HOST="${ARGWS_PONTO_MANAGER_WEBSOCKET_HOST:-$PUBLIC_BIND_HOST}"
  export ARGWS_PONTO_MANAGER_API_ALLOW_PUBLIC_NETWORK="${ARGWS_PONTO_MANAGER_API_ALLOW_PUBLIC_NETWORK:-true}"
  export ARGWS_PONTO_MANAGER_API_CORS="${ARGWS_PONTO_MANAGER_API_CORS:-true}"
  export ARGWS_PONTO_MANAGER_WEB_BIND_LAN="${ARGWS_PONTO_MANAGER_WEB_BIND_LAN:-true}"
  export ARGWS_PONTO_MANAGER_WEBHOOK_ALLOW_LAN="${ARGWS_PONTO_MANAGER_WEBHOOK_ALLOW_LAN:-true}"
  export ARGWS_PONTO_MANAGER_WEBHOOK_ALLOW_EXTERNAL="${ARGWS_PONTO_MANAGER_WEBHOOK_ALLOW_EXTERNAL:-true}"
  export ARGWS_PONTO_MANAGER_WEBSOCKET_ALLOW_LAN="${ARGWS_PONTO_MANAGER_WEBSOCKET_ALLOW_LAN:-true}"
  export ARGWS_PONTO_MANAGER_WEBSOCKET_ALLOW_EXTERNAL="${ARGWS_PONTO_MANAGER_WEBSOCKET_ALLOW_EXTERNAL:-true}"
fi

if bool_true "$START_ALL_PORTS"; then
  export ARGWS_PONTO_MANAGER_WEBHOOK_ENABLED=true
  export ARGWS_PONTO_MANAGER_WEBHOOK_AUTO_START=true
  export ARGWS_PONTO_MANAGER_WEBSOCKET_ENABLED=true
  export ARGWS_PONTO_MANAGER_WEBSOCKET_AUTO_START=true
  export ARGWS_PONTO_MANAGER_SERVICES_AUTO_START=true
fi

export ARGWS_PONTO_MANAGER_ENV_FILE="${ARGWS_PONTO_MANAGER_ENV_FILE:-$ENV_FILE}"
export ARGWS_PONTO_MANAGER_WEB_DIST_DIR="${ARGWS_PONTO_MANAGER_WEB_DIST_DIR:-$APP_DIR/dist}"
export ARGWS_PONTO_MANAGER_DATA_DIR="${ARGWS_PONTO_MANAGER_DATA_DIR:-$APP_DIR/data}"
export ARGWS_PONTO_MANAGER_LOGS_DIR="${ARGWS_PONTO_MANAGER_LOGS_DIR:-$LOG_DIR}"
export ARGWS_PONTO_MANAGER_API_HOST="${ARGWS_PONTO_MANAGER_API_HOST:-127.0.0.1}"
export ARGWS_PONTO_MANAGER_API_PORT="${ARGWS_PONTO_MANAGER_API_PORT:-61001}"
export ARGWS_PONTO_MANAGER_WEB_HOST="${ARGWS_PONTO_MANAGER_WEB_HOST:-127.0.0.1}"

if bool_true "$RESPECT_CLOUDPANEL_PORT" && [[ -n "${PORT:-}" ]]; then
  export ARGWS_PONTO_MANAGER_WEB_PORT="$PORT"
else
  export ARGWS_PONTO_MANAGER_WEB_PORT="${ARGWS_PONTO_MANAGER_WEB_PORT:-61002}"
fi

export ARGWS_PONTO_MANAGER_WEB_ENABLED="${ARGWS_PONTO_MANAGER_WEB_ENABLED:-true}"
export ARGWS_PONTO_MANAGER_WEB_AUTO_START="${ARGWS_PONTO_MANAGER_WEB_AUTO_START:-true}"
export ARGWS_PONTO_MANAGER_SERVICES_AUTO_START="${ARGWS_PONTO_MANAGER_SERVICES_AUTO_START:-true}"
export ARGWS_PONTO_MANAGER_WEBHOOK_HOST="${ARGWS_PONTO_MANAGER_WEBHOOK_HOST:-127.0.0.1}"
export ARGWS_PONTO_MANAGER_WEBHOOK_PORT="${ARGWS_PONTO_MANAGER_WEBHOOK_PORT:-61003}"
export ARGWS_PONTO_MANAGER_WEBSOCKET_HOST="${ARGWS_PONTO_MANAGER_WEBSOCKET_HOST:-127.0.0.1}"
export ARGWS_PONTO_MANAGER_WEBSOCKET_PORT="${ARGWS_PONTO_MANAGER_WEBSOCKET_PORT:-61004}"

ARGS=(
  --mode=headless-api
  --host "$ARGWS_PONTO_MANAGER_API_HOST"
  --port "$ARGWS_PONTO_MANAGER_API_PORT"
  --data-dir "$ARGWS_PONTO_MANAGER_DATA_DIR"
  --start-web-proxy
  --start-services
)

if [[ "${ARGWS_PONTO_MANAGER_WEBHOOK_ENABLED:-false}" == "true" ]]; then
  ARGS+=(--start-webhook)
fi

if [[ "${ARGWS_PONTO_MANAGER_WEBSOCKET_ENABLED:-false}" == "true" ]]; then
  ARGS+=(--start-websocket)
fi

cd "$APP_DIR"
nohup "$BIN_PATH" "${ARGS[@]}" >> "$LOG_FILE" 2>&1 &

echo $! > "$PID_FILE"
echo "Ponto Manager iniciado. PID: $(cat "$PID_FILE")"
echo "WebPort:  http://$ARGWS_PONTO_MANAGER_WEB_HOST:$ARGWS_PONTO_MANAGER_WEB_PORT"
echo "API:      http://$ARGWS_PONTO_MANAGER_API_HOST:$ARGWS_PONTO_MANAGER_API_PORT"
echo "Webhook:  http://$ARGWS_PONTO_MANAGER_WEBHOOK_HOST:$ARGWS_PONTO_MANAGER_WEBHOOK_PORT${ARGWS_PONTO_MANAGER_WEBHOOK_BASE_PATH:-/webhooks} (${ARGWS_PONTO_MANAGER_WEBHOOK_ENABLED:-false})"
echo "WebSocket: ws://$ARGWS_PONTO_MANAGER_WEBSOCKET_HOST:$ARGWS_PONTO_MANAGER_WEBSOCKET_PORT${ARGWS_PONTO_MANAGER_WEBSOCKET_PATH:-/ws} (${ARGWS_PONTO_MANAGER_WEBSOCKET_ENABLED:-false})"
echo "Logs:     $LOG_FILE"
